### ISSUE TITLE
Ejercicio1 - comentario engañoso

### ISSUE THREAD

**Issue by davidosvaldoperez** [sisoputnfrba/so-exercises#4]
[En el ejercicio 1](https://docs.google.com/document/d/1n_u1E8uKzExstQEJR_lJBBsT0P5Ru9kG-yW5VUiYnLs/edit#heading=h.qvs683w5rsg1) se pide implementar:

```c
/*
*   Separa el mail en un usuario y un dominio.
*   Ejemplo:
*   char* mail = "ritchie@ansic.com.ar";
*   char* user, dominio;
*   mail_split(mail, &user, &dominio);
*   =>
*   user = "ritchie"
*   dominio = "ansic.com.ar"
*/
void mail_split(const char* mail, char** user, char** dominio);
```

El problema con el ejemplo del comentario es la declaracion de dominio: lo hace como `char` y no como `char *`. 

Se recomienda:
```
char *user, *dominio;
```
O en dos lineas:
```
char *user;
char *dominio;
```

Gracias

**Comment by gastonprieto** [comment]
Me gusta mas la segunda.
